[tool.poetry]
name = "blockdiag-fences"
version = "0.1.0"
description = "Inline blockdiag images for Markdown with SuperFences"
authors = ["Oliver Salzburg <oliver.salzburg@gmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/oliversalzburg/markdown-blockdiag.git"
keywords = ["blockdiag", "seqdiag", "mkdocs", "markdown", "superfences"]
classifiers = [
	"Development Status :: 4 - Beta",
	"Environment :: Plugins",
	"Intended Audience :: Developers",
	"License :: OSI Approved :: MIT License",
	"Operating System :: OS Independent",
	"Programming Language :: Python :: 3 :: Only",
	"Programming Language :: Python :: 3.8",
	"Topic :: Documentation",
	"Topic :: Software Development :: Documentation",
	"Topic :: Text Processing :: Markup :: Markdown"
]

[tool.poetry.dependencies]
python = ">3.12"
blockdiag = { git = "https://github.com/yuzutech/blockdiag.git", rev = "e2c2b672eb2050a6191dc037f48490e85c56dfca" }
seqdiag = "3.0.0"
nwdiag = "3.0.0"
actdiag = "3.0.0"

[build-system]
requires = ["poetry-core==1.9.0"]
build-backend = "poetry.core.masonry.api"
